### ISSUE TITLE
Issue with getDomTree method

### ISSUE THREAD

**Issue by NikitaMasl** [TobiasJacob/seratolibraryparser#18]
Hello, @TobiasJacob!
I want to get more information about tracks then getSongs method returns. I tried to do it by me own with help of method getDomTree. As i understood this method parse serato *.session files and returns chenk array, but some of the values is broken. Why?
<img width="459" alt="Screenshot 2022-03-09 at 11 42 42" src="https://user-images.githubusercontent.com/48531864/157404771-c9fade67-ed00-4ccd-a1aa-fd3ad856b495.png">
Also in docs you have a list of tags for tracks fields
<img width="785" alt="Screenshot 2022-03-09 at 11 40 53" src="https://user-images.githubusercontent.com/48531864/157404486-5a04d215-f866-4597-9480-9fc4555d242e.png">
where can i find full list?

**Comment by TobiasJacob** [comment]
Hey @NikitaMasl, thanks a lot for opening up an issue. Unfortunately, I was not able to reverse engineer all tags that appear in the serato library. The list you mentioned are then ones that I figured out, but there are a lot of fields I don't know the meaning of.

If you are able to figure out more details, I'm happy to add them to the list.
